name: Create/Publish Release

on:
  push:
    tags:
      - 'v*'

env:
  BIT_GPR_USER: ${{ secrets.BIT_GPR_USER }}
  BIT_GPR_API_KEY: ${{ secrets.BIT_GPR_API_KEY }}
  RELEASE_NAME: ${{ github.ref }}

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set release name
#        run: echo "RELEASE_NAME=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            What is new :
              - First Change
              - Second Change
          draft: false
          prerelease: false

  publish:
    name: Publish Build
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build AAR
        run: ./gradlew clean assemble

      - name: Publish library
        run: ./gradlew publish

      - name: Upload AAR
        uses: actions/upload-artifact@v2
        with:
          name: release-aar
          path: pagedlist/build/outputs/aar/pagedlist-release.aar