name: Release CD/CI

# Step 1: Choose the branch or branches you want to run this workflow
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  BIT_GPR_USER: ${{ secrets.BIT_GPR_USER }}
  BIT_GPR_API_KEY: ${{ secrets.BIT_GPR_API_KEY }}

jobs:

  removeOldArtifacts:
    name: Remove Old Artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Run job
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '15 days'
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5

  lintRelease:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check Lint
        run: ./gradlew :pagedlist:lint

      - name: Lint results
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
        with:
          name: lint-check-result
          path: pagedlist/build/reports/lint-results.html

  testRelease:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check Unit tests
        run: ./gradlew :pagedlist:test

      - name: Unit test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
        with:
          name: unit-tests-results
          path: pagedlist/build/reports/tests/testReleaseUnitTest/index.html